### ISSUE TITLE
when would you upload the code?

### ISSUE THREAD

**Issue by Daixinxin-cc** [SMohammadi89/PointView-GCN#1]
Hi, i am very interested in your paper, when would you upload the code? i am looking forward that.

**Comment by Daixinxin-cc** [comment]
> > Hi, i am very interested in your paper, when would you upload the code? i am looking forward that.
> 
> Hi Daixinxian, thanks for your interest in our work. Most probably we will release the code by the end of this month, or maximum after one month.

one month has passed....you still didn't upload code😊

**Comment by SaberMohammadi** [comment]
HI @Daixinxin-cc really sorry, now I am busy with cvpr deadline. I will release the code after the deadline here for sure. sorry again

**Comment by gianscarpe** [comment]
Hi @SaberMohammadi , I'm very upset. Do you plan to upload the code soon?
Thanks

**Comment by Daixinxin-cc** [comment]
> implemented



> HI @Daixinxin-cc really sorry, now I am busy with cvpr deadline. I will release the code after the deadline here for sure. sorry again

Ok, I am compiling the code, but I have some problems that I can't solve, I will try to solve these problems until you load the code, good luck for your cvpr paper :）

**Comment by SMohammadi89** [comment]
@Daixinxin-cc the code is ready to use
